
/**************************************************************
 *	
 *	up, 8 bit, 11025Hz,
 *	1 channel, 11054 bytes/channel
 *	Total Size: 1 * 11054 + 4 (header) = 11098 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\10ala\Documents\GT Fall 2019\CS 2261\RiverDrifter\FinalProject\up.wav
 *	Time-stamp: Tue Dec 03 13:20:25 2019
 *	
 **************************************************************/

#ifndef __UPH__
#define __UPH__

#define UPFREQ 11025
#define UPLEN 11054

extern const unsigned char up[11054];

#endif /* __UPH__ */
