
/**************************************************************
 *	
 *	moonRiver, 8 bit, 11025Hz,
 *	1 channel, 2077344 bytes/channel
 *	Total Size: 1 * 2077344 + 4 (header) = 2077388 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\10ala\Documents\GT Fall 2019\CS 2261\RiverDrifter\M04\moonRiver.wav
 *	Time-stamp: Wed Nov 20 12:48:36 2019
 *	
 **************************************************************/

#ifndef __MOONRIVERH__
#define __MOONRIVERH__

#define MOONRIVERFREQ 11025
#define MOONRIVERLEN 2077344

extern const unsigned char moonRiver[2077344];

#endif /* __MOONRIVERH__ */
