
/**************************************************************
 *	
 *	powerDown, 8 bit, 11025Hz,
 *	1 channel, 20513 bytes/channel
 *	Total Size: 1 * 20513 + 4 (header) = 20557 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\10ala\Documents\GT Fall 2019\CS 2261\RiverDrifter\M04\powerDown.wav
 *	Time-stamp: Tue Nov 26 14:24:19 2019
 *	
 **************************************************************/

#ifndef __POWERDOWNH__
#define __POWERDOWNH__

#define POWERDOWNFREQ 11025
#define POWERDOWNLEN 20513

extern const unsigned char powerDown[20513];

#endif /* __POWERDOWNH__ */
