
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 202411 bytes/channel
 *	Total Size: 1 * 202411 + 4 (header) = 202455 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\10ala\Documents\GT Fall 2019\CS 2261\RiverDrifter\M04\TitleSong.wav
 *	Time-stamp: Wed Nov 20 17:00:53 2019
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 202411

extern const unsigned char TitleSong[202411];

#endif /* __TITLESONGH__ */
